version: '3.8'

services:
  app:
    build: .
    container_name: task-manager-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - task-net
    volumes:
      - .:/app

  mongo:
    image: mongo:6.0
    container_name: task-manager-db
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - task-net

volumes:
  mongo-data:

networks:
  task-net:
    driver: bridge
