version: '3.8'

services:
  app:
    build: .
    container_name: task-manager-api
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - task-net
    volumes:
      - .:/app

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    command: [ "mongod", "--auth" ]
    volumes:
      - mongo_data:/data/db
    networks:
      - task-net
    environment:
      - MONGO_INITDB_DATABASE=es1
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mongo_data:

networks:
  task-net:
    driver: bridge
